require:
  - rubocop-minitest

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Semicolon:
  AllowAsExpressionSeparator: true

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y

